### ISSUE TITLE
zappar-threejs `0.3.33` incompatible with ThreeJS `0.136.0` (latest)

### ISSUE THREAD

**Issue by FarazzShaikh** [zappar-xr/zappar-threejs#135]
**Describe the bug**
Latest version of Zappar-threejs throws 
```
THREE.ImmediateRenderObject has been removed.
```
when running with latest version of ThreeJS (`0.136.0`)

**To Reproduce**
1. Clone `zappar-threejs-instant-tracking-webpack-bootstrap-typescript`
2. Run `npm install` in root folder
3. Run `npm install three@latest` in root folder
4. Start dev server using `npm run dev-server`
5. Observe error in dev tools and no white cube as you'd expect

**Expected behavior**
Zappar to work with the latest release of ThreeJS

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome
 - Version: 97.0.4692.71

**Additional context**
This is fixed when replacing [this line](https://github.com/zappar-xr/zappar-threejs/blob/2fcd0f7384ffa5d077e6f4b88ee0f107ed0114ee/src/camera.ts#L215) with 
```ts
  const immediate = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());
```
I'm not sure what the consequences of doing so are, but in my testing it seems to work just fine after.

**Comment by nyan-left** [comment]
hey @FarazzShaikh ,

Thanks for the report! 

We are aware of this issue and are working on a patch. In the meantime, I would recommend sticking to our defined [dependency range](https://github.com/zappar-xr/zappar-threejs/blob/master/package.json#L76).

The workaround you defined will produce WebGL errors ( if you check your console, you'll see it complaining about no bound buffer ), which may cause errors down the line. 

Shall update the thread once we have a fix out :)

**Comment by FarazzShaikh** [comment]
Gotcha, thanks for the quick response.
