### ISSUE TITLE
cameraFrameTextureGL undefined

### ISSUE THREAD

**Issue by amaau** [zappar-xr/zappar-threejs#137]
**Describe the bug**
Sorry for writing here, I can't find any "core" repository to write to.
I'm following the javascript [getting started guide](https://docs.zap.works/universal-ar/javascript/getting-started/usage/), and I have a problem with the camera.
I see that it's recording, but pipeline.cameraFrameDrawGL does nothing, and pipeline.cameraFrameTextureGL always returns undefined.
It does not matter if I'm using a CameraSource or an HTMLElementSource

There are tons of examples for all the frameworks on Github, but I couldn't find a single example / code sandbox that demonstrates basic usage without any framework.

I just need to get the tracked image coordinates, everything I do with them afterwards is in 2D, and any 3D framework is an unnecessary burden.

Thanks and sorry again for posting here. If there's a more fitting channel please let me know

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 97, 64 bit

**Comment by nyan-left** [comment]
Hi @amaau ,

No worries. I'd suggest posting questions to [our forums ](https://forum.zap.works/c/universal-ar/30) in the future. 

Are you able to share a minimal repo/codesandbox, demonstrating the issue?

**Comment by amaau** [comment]
Hi @nyan-left , thanks for helping!

Here's a [demo](https://codesandbox.io/s/falling-firefly-sgwzz?file=/src/index.js)
It appears codesandbox has issues with Zappar, as soon as I imported the package I got many errors, hope it will run on your end, but in any case you should see any errors I may have.

**Comment by nyan-left** [comment]
I don't really see anything out of the ordinary, you should request camera permissions though:
```js
Zappar.permissionRequestUI().then((granted) => {
  //...
});
```
Is it possible that your webpack config is missing the wasm setup?

```js
module.exports = {
  //...
  module: {
    rules: [
      //...
      {
        test: /zcv\.wasm$/,
        type: "javascript/auto",
        loader: "file-loader"
      }
      //...
    ]
  }
};
```


I've set up a minimal, working repo you can take a look at here:
https://github.com/nyan-left/zappar-js-example
https://nyan-left.github.io/zappar-js-example/

**Comment by amaau** [comment]
Thank you very very much!

(permissions are ok and i didn't forget wasm, but now that i have a working example i'll figure it out and post here once i do)

**Comment by amaau** [comment]
I solved the issue, it was related to webpack but not the wasm rule - 
Many errors only showed at build time, while in dev mode Zappar failed silently. The errors are the same ones you see if you try opening my codesandbox - "'exports' is not defined", "x is not a constructor", some error in file-loader etc.

In this project I had a webpack config inherited from CRA, that was too complicated for me to figure out. Once I replaced it with a webpack config I made myself everything started working.

But I think it indicates you may have an issue with the way Zappar modules are organized / exported / relative imports / ? 

Anyway, thanks for your help!

**Comment by nyan-left** [comment]
Nice, thanks for the update. 

When using CRA, you need to add two additional bits of config to webpack, using something like [react-app-rewired](https://github.com/timarney/react-app-rewired) if you wish to avoid ejecting.

1. WASM `file-loader `rule - As you noted, you already have this.
2. `config.resolve.extensions` requires a ".wasm" value. 

I think you may be missing the 2nd point. Here's a `config-overrides.js ` that you can use with CRA and react-scripts-rewired:

https://github.com/zappar-xr/zappar-react-three-fiber-instant-tracking-webpack-bootstrap-typescript/blob/master/config-overrides.js

I hope this helps!

**Comment by amaau** [comment]
Thanks @nyan-left !
It wasn't either that actually, I noticed the ".wasm" in the extentions part of the working example project you posted, and so before ditching the CRA config I first tried copying it over (I've already had it ejected), but it didn't help. 
I suspect some module resolution settings I've had there conflicted with relative imports / requires in the Zappar package.

The errors I was getting are the same that will show up if you try running my codesandbox example (which wasn't based on CRA), so if you're curious about it and have the spare time, you could try fixing it in codesandbox and then we'll know for sure what was the issue.

**Comment by nyan-left** [comment]
Shall take a look! 👍
