### ISSUE TITLE
Allow configuring `far` for Three's camera

### ISSUE THREAD

**Issue by gilbert** [zappar-xr/zappar-threejs#22]
We need to increase Three's `far` value to increase draw distance in our app. However, Zappar is currently hiding Three's camera behind [its own abstraction](https://github.com/zappar-xr/zappar-threejs/blob/master/src/camera.ts#L139), so there's no way to do this.

**Comment by nyan-left** [comment]
Hi @gilbert ,

Thanks for the feedback!

We're working on getting this exposed. I will update and close this issue once the feature has made it's way to the package :)

**Comment by nyan-left** [comment]
This has now been released :) 

https://github.com/zappar-xr/zappar-threejs/compare/0.3.23...0.3.24
