### ISSUE TITLE
No ESM support when bundling with webpack

### ISSUE THREAD

**Issue by Hless** [zappar-xr/zappar-threejs#310]
**Describe the bug**
In our project we use the @zappar/zappar-react-three-fiber library. When including components, webpack assumes the zappar-react-three library to be a CJS module. The underlying three.js module also gets included as a CJS module because of this. As a result, when importing from three directly (as an ES module) into our project, we end up with two versions of three in the project (ESM and CJS). 

**To Reproduce**
Bundle @zappar/zappar-react-three-fiber with a react app created with a recent CRA version. Couple of things to consider:

- Older versions of CRA may not work, because it seems that Webpack 4 support is also broken (because of references to import.meta.url in zappar-cv)
- Newer versions of CRA may not work out of the box, because the default webpack config has issues importing`.cjs` modules, which three exports.

**Expected behavior**
Expect correct handling of both CJS and ESM bundling in webpack.

**Smartphone:**
N/A

**Comment by nyan-left** [comment]
Hi @Hless,

We have recently updated the Universal AR npm packages and made changes to the build target, setting it to `esm`. This modification has resolved the `react-scripts@5` compatibility issue that was present with .cjs loading. This update will enable the recent versions of Create React App (CRA) to function properly, given that the HTTPS flag is enabled.

With regards to the issue of multiple instances of `THREE` being bundled, we request you kindly check if this issue persists in the production build. Our investigation has shown that this issue can only be recreated during development. 
You can verify this by utilizing a tool like `source-map-explorer`. According to the three forums, this is a common issue faced with three and webpack.


To resolve this issue (during development), it is recommended to provide a three resolve alias to webpack, which can be achieved through the use of the [customize-cra](https://github.com/arackaf/customize-cra) library. 

```js
three: path.resolve('./node_modules/three')
```

**Comment by Hless** [comment]
Hi @nyan-left 

We did end up with two THREE instances in our production bundle, also caused issues with `instanceof` checking etcetera. This happened with the babel-loader in webpack. We did use source-map-explorer to verify, and both the ESM and CJS version of threejs were present. 

Perhaps it depends on configuration, but as far as I am aware, CJS modules can not import ESM modules, so you should always end up with multiple instance of three. It could be that you were compiling your own sources down to CJS in the first place? In that case, your own code will also import three as a CJS module, and you will not experience the double import issue.
 
Anyhow, after upgrading to `@zappar/zappar-react-three-fiber@2.2.0` this issue went away. Bundle size is now reduced drastically :)!

Thanks for the update and clarification.

**Comment by nyan-left** [comment]
Hi @Hless,

Thank you for the update and for providing additional information regarding the issue of multiple instances of `THREE` being bundled in production. We're glad to hear that upgrading to `@zappar/zappar-react-three-fiber@2.2.0` resolved the issue for you and reduced the bundle size.

If you have any further questions or concerns, please don't hesitate to reach out to us :)
